---
- name: Pre-kubernetes install tasks
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade 
      shell: yum update -y && yum upgrade -y
    - name: Install vim
      shell: yum install -y vim mlocate

